name: tf-main-wf

on:
  push:
    branches: [ main, develop, 'sprint/**', 'release/**' ]
  pull_request:
    branches: [ main, develop, 'sprint/**', 'release/**' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  infra-L1:
    uses: rdkcentral/entservices-infra/.github/workflows/L1-tests.yml@develop
    with:
      caller_source: testframework

  infra-L2:
    uses: rdkcentral/entservices-infra/.github/workflows/L2-tests.yml@develop
    with:
      caller_source: testframework

  softwareupdate-L1:
    uses: rdkcentral/entservices-softwareupdate/.github/workflows/L1-tests.yml@develop
    with:
      caller_source: testframework

  softwareupdate-L2:
    uses: rdkcentral/entservices-softwareupdate/.github/workflows/L2-tests.yml@develop
    with:
      caller_source: testframework

  firmwareupdate-L1:
    uses: rdkcentral/entservices-firmwareupdate/.github/workflows/L1-tests.yml@develop
    with:
      caller_source: testframework

  firmwareupdate-L2:
    uses: rdkcentral/entservices-firmwareupdate/.github/workflows/L2-tests.yml@develop
    with:
      caller_source: testframework

  casting-L1:
    uses: rdkcentral/entservices-casting/.github/workflows/L1-tests.yml@develop
    with:
      caller_source: testframework

  mediaanddrm-L1:
    uses: rdkcentral/entservices-mediaanddrm/.github/workflows/L1-tests.yml@feature/RDKEMW-12936
    with:
      caller_source: testframework

  mediaanddrm-L2:
    uses: rdkcentral/entservices-mediaanddrm/.github/workflows/L2-tests.yml@develop
    with:
      caller_source: testframework
      
  peripherals-L1:
    uses: rdkcentral/entservices-peripherals/.github/workflows/L1-tests.yml@develop
    with:
      caller_source: testframework
  
  ledcontrol-L2:
    uses: rdkcentral/entservices-ledcontrol/.github/workflows/L2-tests.yml@develop
    with:
      caller_source: testframework
  
  frontpanel-L1:
    uses: rdkcentral/entservices-frontpanel/.github/workflows/L1-tests.yml@develop
    with:
      caller_source: testframework

  hdmicecsource-L1:
    uses: rdkcentral/entservices-hdmicecsource/.github/workflows/L1-tests.yml@develop
    with:
      caller_source: testframework

  hdmicecsource-L2:
    uses: rdkcentral/entservices-hdmicecsource/.github/workflows/L2-tests.yml@develop
    with:
      caller_source: testframework

  hdmicecsink-L1:
    uses: rdkcentral/entservices-hdmicecsink/.github/workflows/L1-tests.yml@develop
    with:
      caller_source: testframework

  hdmicecsink-L2:
    uses: rdkcentral/entservices-hdmicecsink/.github/workflows/L2-tests.yml@develop
    with:
      caller_source: testframework

  hdcpprofile-L1:
    uses: rdkcentral/entservices-hdcpprofile/.github/workflows/L1-tests.yml@develop
    with:
      caller_source: testframework

  hdcpprofile-L2:
    uses: rdkcentral/entservices-hdcpprofile/.github/workflows/L2-tests.yml@develop
    with:
      caller_source: testframework

  avinput-L1:
    uses: rdkcentral/entservices-avinput/.github/workflows/L1-tests.yml@develop
    with:
      caller_source: testframework

  avinput-L2:
    uses: rdkcentral/entservices-avinput/.github/workflows/L2-tests.yml@develop
    with:
      caller_source: testframework

  linearplaybackcontrol-L1:
    uses: rdkcentral/entservices-linearplaybackcontrol/.github/workflows/L1-tests.yml@develop
    with:
      caller_source: testframework

  linearplaybackcontrol-L2:
    uses: rdkcentral/entservices-linearplaybackcontrol/.github/workflows/L2-tests.yml@develop
    with:
      caller_source: testframework

  playerinfo-L1:
    uses: rdkcentral/entservices-playerinfo/.github/workflows/L1-tests.yml@develop
    with:
      caller_source: testframework

  playerinfo-L2:
    uses: rdkcentral/entservices-playerinfo/.github/workflows/L2-tests.yml@develop
    with:
      caller_source: testframework

  screencapture-L1:
    uses: rdkcentral/entservices-screencapture/.github/workflows/L1-tests.yml@develop
    with:
      caller_source: testframework

  screencapture-L2:
    uses: rdkcentral/entservices-screencapture/.github/workflows/L2-tests.yml@develop
    with:
      caller_source: testframework

  unifiedcasmanagement-L1:
    uses: rdkcentral/entservices-unifiedcasmanagement/.github/workflows/L1-tests.yml@develop
    with:
      caller_source: testframework

  unifiedcasmanagement-L2:
    uses: rdkcentral/entservices-unifiedcasmanagement/.github/workflows/L2-tests.yml@develop
    with:
      caller_source: testframework

  devicediagnostics-L1:
    uses: rdkcentral/entservices-devicediagnostics/.github/workflows/L1-tests.yml@feature/RDKEMW-14703
    with:
      caller_source: testframework

  devicediagnostics-L2:
    uses: rdkcentral/entservices-devicediagnostics/.github/workflows/L2-tests.yml@feature/RDKEMW-14703
    with:
      caller_source: testframework

  deviceinfo-L1:
    uses: rdkcentral/entservices-deviceinfo/.github/workflows/L1-tests.yml@develop
    with:
      caller_source: testframework

  deviceinfo-L2:
    uses: rdkcentral/entservices-deviceinfo/.github/workflows/L2-tests.yml@develop
    with:
      caller_source: testframework

  displayinfo-L1:
    uses: rdkcentral/entservices-displayinfo/.github/workflows/L1-tests.yml@develop
    with:
      caller_source: testframework

  displaysettings-L2:
    uses: rdkcentral/entservices-displaysettings/.github/workflows/L2-tests.yml@develop
    with:
      caller_source: testframework

  framerate-L1:
    uses: rdkcentral/entservices-framerate/.github/workflows/L1-tests.yml@develop
    with:
      caller_source: testframework

  framerate-L2:
    uses: rdkcentral/entservices-framerate/.github/workflows/L2-tests.yml@develop
    with:
      caller_source: testframework

  powermanager-L1:
    uses: rdkcentral/entservices-powermanager/.github/workflows/L1-tests.yml@develop
    with:
      caller_source: testframework

  powermanager-L2:
    uses: rdkcentral/entservices-powermanager/.github/workflows/L2-tests.yml@develop
    with:
      caller_source: testframework

  powermanager-L2-oop:
    uses: rdkcentral/entservices-powermanager/.github/workflows/L2-tests-oop.yml@develop
    with:
      caller_source: testframework

  systemmode-L2:
    uses: rdkcentral/entservices-systemmode/.github/workflows/L2-tests.yml@develop
    with:
      caller_source: testframework

  systemservices-L1:
    uses: rdkcentral/entservices-systemservices/.github/workflows/L1-tests.yml@develop
    with:
      caller_source: testframework

  systemservices-L2:
    uses: rdkcentral/entservices-systemservices/.github/workflows/L2-tests.yml@develop
    with:
      caller_source: testframework

  userpreferences-L1:
    uses: rdkcentral/entservices-userpreferences/.github/workflows/L1-tests.yml@develop
    with:
      caller_source: testframework

  userpreferences-L2:
    uses: rdkcentral/entservices-userpreferences/.github/workflows/L2-tests.yml@develop
    with:
      caller_source: testframework

  warehouse-L1:
    uses: rdkcentral/entservices-warehouse/.github/workflows/L1-tests.yml@develop
    with:
      caller_source: testframework

  warehouse-L2:
    uses: rdkcentral/entservices-warehouse/.github/workflows/L2-tests.yml@develop
    with:
      caller_source: testframework
